# Generated by Django 4.1.1 on 2022-09-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('do', models.CharField(max_length=122)),
                ('status', models.CharField(max_length=122)),
            ],
        ),
    ]
